### ISSUE TITLE
Doesn't seem to support approaches of leading scientists in the field of aging 

### ISSUE THREAD

**Issue by dhiahassen** [MaximilianKohler/HumanMicrobiome#3]
I have been in the field of aging biochemistry for some years now, and I consume materials aboutthe topic on a daily basis, so maybe I can have an opinion on this.
Around the globe, the most tow appreciated approaches in the field on anti aging seem to be "7 types of damage" of SENSE foundation introduced by Aubrey de grey in his book of 2007
And "theory of loss of epigentic information" introduced by David Sinclair, and reintroduced recently in his book "life span" in 2019 
Those two approaches are high and increasingly authentized by the community of anti aging research, and are giving positive results in clinical trials in the past years.. so maybe you want to take a look on that and think of possibly referencing it in your wiki

**Comment by MaximilianKohler** [comment]
If you have specific studies/reviews to suggest feel free, but that sounds like it's beyond the scope of this site.
