### ISSUE TITLE
You're all over the place!

### ISSUE THREAD

**Issue by throwawaycar** [MaximilianKohler/HumanMicrobiome#5]
You're all over the place. Can't tell whether you're saying probiotics are good or bad! If good, which particular strains are good (and for what purpose) and how to ingest them or ensure they colonize your gut? If bad, then just summarize and highlight that in bold.

**Comment by MaximilianKohler** [comment]
>You're all over the place

The science is not at clear cut as you're wanting it to be. 

>If good, which particular strains are good (and for what purpose) 
>how to ingest them or ensure they colonize your gut? 

That already exists in the probiotic guide. 

>If bad, then just summarize and highlight that in bold.

Again, the science isn't that clear. The probiotic guide clearly states this. That it is largely up to individual experimentation. Additionally, the Probiotics page does have a section on harms.
