### ISSUE TITLE
Replace dead link in the Testing section

### ISSUE THREAD

**Issue by stuux** [MaximilianKohler/HumanMicrobiome#8]
The link to the example report of the Diagnostic Solutions GI Map is dead. See below:

 https://www.diagnosticsolutionslab.com/sites/default/files/GI-MAP-Sample-Report_ARs.pdf
![image](https://user-images.githubusercontent.com/65719148/196388912-9c1604d1-1e13-4561-9921-45dcbdef43fb.png)

This should be the correct link for now:

https://www.diagnosticsolutionslab.com/sites/default/files/GI-MAP-Sample-Report.pdf

**Comment by MaximilianKohler** [comment]
Done. Thanks.

**Comment by stuux** [comment]
I have found a few more dead links. Would you prefer it if I open a new issue for each one, or should I post them under this issue?

**Comment by stuux** [comment]
All the following errors were found in the [HumanMicrobiome.info#commercial-testing](http://humanmicrobiome.info/#commercial-testing) section.

**Comment by stuux** [comment]
> Here are a few articles questioning the accuracy of these tests: [[1](https://mrheisenbug.wordpress.com/2014/04/24/dear-american-gut-ubiome-you-have-some-explaining-to-do)][[2](https://www.sciencenews.org/article/big-data-studies-come-replication-challenges)][[3](https://www.sciencenews.org/blog/gory-details/here%E2%80%99s-poop-getting-your-gut-microbiome-analyzed)]

First reference leads to a private website:

https://mrheisenbug.wordpress.com/2014/04/24/dear-american-gut-ubiome-you-have-some-explaining-to-do

![image](https://user-images.githubusercontent.com/65719148/196716213-bb39c254-5431-483c-914c-0f1947e7bba9.png)


Maybe replace  this by a webarchive snapshot?

http://web.archive.org/web/20170807141515/https://mrheisenbug.wordpress.com/2014/04/24/dear-american-gut-ubiome-you-have-some-explaining-to-do/

**Comment by stuux** [comment]
> Here's an [example report from Biocollective.com](https://www.scribd.com/document/353870827/16s-Stool-Results-Biocollective-2016).

Link leads to a different website.

![image](https://user-images.githubusercontent.com/65719148/196716672-71908e31-8430-495e-91f2-57c99ff1c647.png)

And biocollectiv.com is for sale:

![image](https://user-images.githubusercontent.com/65719148/196716959-922da3b1-c2f8-45d9-967d-f6a7045f24ec.png)

Should it have been https://www.thebiocollective.com/ instead? But I dont know if they still sell tests.

**Comment by stuux** [comment]
> Example report from [Genova's GI Effects](http://www.smartnutrition.co.uk/wp-content/uploads/2014/10/Smart-Nutrition-GI-Effects-Microbial-Ecology-Sample-Report1.pdf).

This link is working, but leading to an older example report of the Genova's GI Effects test. Maybe replace it with this newer version?

https://www.gdx.net/core/sample-reports/gi-effects-2200-sample-report.pdf

**Comment by stuux** [comment]
> Directlabs.com has a variety of tests: https://www.directlabs.com/pop/OrderTests/tabid/35269/language/en-US/Default.aspx 

This link leads to a 404.

![image](https://user-images.githubusercontent.com/65719148/196718234-d893d065-c793-4646-b54c-2a1b7e04620a.png)

Replace it with this link https://store.directlabs.com/ instead?

**Comment by MaximilianKohler** [comment]
Thanks! Updated. 

> Directlabs.com has a variety of tests
> This link leads to a 404.

That's a shame. Their new layout is quite bad.

**Comment by stuux** [comment]
> Example report from [Diagnostic Solutions GI Map](https://www.diagnosticsolutionslab.com/tests/gi-map): https://www.diagnosticsolutionslab.com/sites/default/files/GI-MAP-Sample-Report_ARs.pdf - this one seems very useful.

The link to the example report still seems to be outdated.

**Comment by MaximilianKohler** [comment]
Hmm, odd. Updated it again.

**Comment by stuux** [comment]
Now it's the correct link.
